### ISSUE TITLE
Looking for "Performance Modeling with Aspen"

### ISSUE THREAD

**Issue by richardlford** [kspaff/kspaff.github.io#1]
In the paper, "Aspen: A Domain Specific Language for Performance Modeling", reference [22] is to 

K. Spafford and J. Vetter, "Peformance Modeling with aspen", Oak Ridge National Laboratory Technical Report 2012-01. Available https://kylespafford.com/aspen.html

However, the document does not seem to be at that URL any more. As you were one of the authors:

- Do you know where this document is available, or perhaps a more updated version of the Aspen specification
- Is the Aspen modeling software still available? Is it still in use?

Thanks.
Richard L Ford

**Comment by kspaff** [comment]
Hi Richard - unfortunately, I did not retain a copy of that technical report. The information in the IEEE paper is probably the best record of the Aspen project. I do not think the project was actively maintained after I moved on and is probably best used as inspiration for your performance model.

**Comment by richardlford** [comment]
OK. Thanks.
